/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlignmentGuides: typeof import('./src/components/AlignmentGuides.vue')['default']
    CollapsibleSection: typeof import('./src/components/controls/CollapsibleSection.vue')['default']
    ColorPicker: typeof import('./src/components/controls/ColorPicker.vue')['default']
    DropTargetOverlay: typeof import('./src/components/DropTargetOverlay.vue')['default']
    Guides: typeof import('./src/components/Guides.vue')['default']
    ImageElement: typeof import('./src/components/ImageElement.vue')['default']
    ImageProperties: typeof import('./src/components/ImageProperties.vue')['default']
    LucideBan: typeof import('~icons/lucide/ban')['default']
    LucideChevronDown: typeof import('~icons/lucide/chevron-down')['default']
    LucideChevronRight: typeof import('~icons/lucide/chevron-right')['default']
    LucideChevronUp: typeof import('~icons/lucide/chevron-up')['default']
    LucidePlus: typeof import('~icons/lucide/plus')['default']
    MediaProperties: typeof import('./src/components/MediaProperties.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    NavigationPanel: typeof import('./src/components/NavigationPanel.vue')['default']
    NumberInput: typeof import('./src/components/controls/NumberInput.vue')['default']
    PresentationActionDialog: typeof import('./src/components/PresentationActionDialog.vue')['default']
    PresentationHeader: typeof import('./src/components/PresentationHeader.vue')['default']
    PresentationList: typeof import('./src/components/PresentationList.vue')['default']
    PresentationPreview: typeof import('./src/components/PresentationPreview.vue')['default']
    PropertiesPanel: typeof import('./src/components/PropertiesPanel.vue')['default']
    ResizeHandle: typeof import('./src/components/ResizeHandle.vue')['default']
    Resizer: typeof import('./src/components/Resizer.vue')['default']
    Resizer1: typeof import('./src/components/Resizer1.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectionBox: typeof import('./src/components/SelectionBox.vue')['default']
    SlideContainer: typeof import('./src/components/SlideContainer.vue')['default']
    SlideElement: typeof import('./src/components/SlideElement.vue')['default']
    SlideProperties: typeof import('./src/components/SlideProperties.vue')['default']
    SliderInput: typeof import('./src/components/controls/SliderInput.vue')['default']
    SnapGuides: typeof import('./src/components/SnapGuides.vue')['default']
    TextElement: typeof import('./src/components/TextElement.vue')['default']
    TextProperties: typeof import('./src/components/TextProperties.vue')['default']
    Toolbar: typeof import('./src/components/Toolbar.vue')['default']
    VideoElement: typeof import('./src/components/VideoElement.vue')['default']
    VideoProperties: typeof import('./src/components/VideoProperties.vue')['default']
  }
}
